#!/usr/bin/bash

for arg in "$@"; do
    case $arg in
        install)
            shift
            pacman --color=auto -S "$@"
            ;;
        search)
            shift
            pacman --color=auto -Ss "$@"
            ;;
        remove)
            shift
            pacman --color=auto -R "$@"
            ;;
        upgrade)
            shift
            pacman --color=auto -Syu "$@"
            ;;
    esac
done
